import type { ComponentType } from "react";
import {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiTypescript,
  SiTailwindcss,
  SiHtml5,
  SiRedux,
  SiNodedotjs,
  SiPython,
  SiGo,
  SiExpress,
  SiFastapi,
  SiSpring,
  SiGraphql,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiAmazonwebservices,
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiTensorflow,
  SiPytorch,
  SiOpenai,
  SiScikitlearn,
  SiPandas,
  SiSolidity,
  SiEthereum,
  SiPolygon,
  SiWeb3Dotjs,
  SiIpfs,
  SiRust,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiMysql,
  SiFirebase,
  SiSupabase,
  SiElasticsearch,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiGithubactions,
  SiJenkins,
  SiNginx,
  SiPrometheus,
  SiLangchain,
  SiAnthropic,
  SiClaude,
  SiGooglegemini,
  SiMeta,
  SiDigitalocean,
  SiOracle,
  SiApachecordova,
  SiDotnet,
  SiRubyonrails,
  SiApachespark,
  SiScala,
  SiSap,
  SiAlchemy,
  SiApple,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";
import {
  Cable,
  Cloud,
  Database,
  GitBranch,
  HardHat,
  Link,
  Play,
  Smartphone,
  SmilePlus,
  TreePine,
  Workflow,
} from "lucide-react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type IconComponent = ComponentType<any>;

interface TechIcon {
  icon: IconComponent;
  color: string;
}

export const techIconMap: Record<string, TechIcon> = {
  // Frontend
  react: { icon: SiReact, color: "#61DAFB" },
  nextjs: { icon: SiNextdotjs, color: "#000000" },
  vuejs: { icon: SiVuedotjs, color: "#4FC08D" },
  angular: { icon: SiAngular, color: "#DD0031" },
  typescript: { icon: SiTypescript, color: "#3178C6" },
  tailwindcss: { icon: SiTailwindcss, color: "#06B6D4" },
  html5: { icon: SiHtml5, color: "#E34F26" },
  redux: { icon: SiRedux, color: "#764ABC" },

  // Backend
  nodejs: { icon: SiNodedotjs, color: "#339933" },
  python: { icon: SiPython, color: "#3776AB" },
  java: { icon: FaJava, color: "#007396" },
  go: { icon: SiGo, color: "#00ADD8" },
  expressjs: { icon: SiExpress, color: "#000000" },
  fastapi: { icon: SiFastapi, color: "#009688" },
  spring: { icon: SiSpring, color: "#6DB33F" },
  graphql: { icon: SiGraphql, color: "#E10098" },
  api: { icon: Cable, color: "#6B7280" },
  scala: { icon: SiScala, color: "#DC322F" },
  play: { icon: Play, color: "#646464" },
  akka: { icon: Workflow, color: "#15A9CE" },
  dotnet: { icon: SiDotnet, color: "#512BD4" },
  rubyonrails: { icon: SiRubyonrails, color: "#CC0000" },
  apachespark: { icon: SiApachespark, color: "#E25A1C" },

  // Mobile
  flutter: { icon: SiFlutter, color: "#02569B" },
  swift: { icon: SiSwift, color: "#F05138" },
  kotlin: { icon: SiKotlin, color: "#7F52FF" },
  objectivec: { icon: SiApple, color: "#000000" },
  cordova: { icon: SiApachecordova, color: "#E8E8E8" },
  oraclemaf: { icon: Smartphone, color: "#F80000" },
  sapmobileplatform: { icon: SiSap, color: "#0FAAFF" },

  // Cloud
  aws: { icon: SiAmazonwebservices, color: "#FF9900" },
  gcp: { icon: SiGooglecloud, color: "#4285F4" },
  azure: { icon: Cloud, color: "#0078D4" },
  vercel: { icon: SiVercel, color: "#000000" },
  netlify: { icon: SiNetlify, color: "#00C7B7" },
  digitalocean: { icon: SiDigitalocean, color: "#0080FF" },

  // AI & ML
  tensorflow: { icon: SiTensorflow, color: "#FF6F00" },
  pytorch: { icon: SiPytorch, color: "#EE4C2C" },
  openai: { icon: SiOpenai, color: "#412991" },
  langchain: { icon: SiLangchain, color: "#1C3C3C" },
  langgraph: { icon: GitBranch, color: "#1C3C3C" },
  huggingface: { icon: SmilePlus, color: "#FFD21E" },
  awsbedrock: { icon: SiAmazonwebservices, color: "#FF9900" },
  claude: { icon: SiClaude, color: "#D97757" },
  llama3: { icon: SiMeta, color: "#0668E1" },
  gemini: { icon: SiGooglegemini, color: "#8E75B2" },
  chroma: { icon: Database, color: "#FC8181" },
  pinecone: { icon: TreePine, color: "#1A9F75" },
  scikitlearn: { icon: SiScikitlearn, color: "#F7931E" },
  pandas: { icon: SiPandas, color: "#150458" },
  anthropic: { icon: SiAnthropic, color: "#D97757" },

  // Blockchain
  solidity: { icon: SiSolidity, color: "#363636" },
  ethereum: { icon: SiEthereum, color: "#3C3C3D" },
  polygon: { icon: SiPolygon, color: "#8247E5" },
  hardhat: { icon: HardHat, color: "#FFF100" },
  web3js: { icon: SiWeb3Dotjs, color: "#F16822" },
  ipfs: { icon: SiIpfs, color: "#65C2CB" },
  rust: { icon: SiRust, color: "#000000" },
  alchemy: { icon: SiAlchemy, color: "#0C0C0C" },

  // Database
  postgresql: { icon: SiPostgresql, color: "#4169E1" },
  mongodb: { icon: SiMongodb, color: "#47A248" },
  redis: { icon: SiRedis, color: "#DC382D" },
  mysql: { icon: SiMysql, color: "#4479A1" },
  firebase: { icon: SiFirebase, color: "#FFCA28" },
  supabase: { icon: SiSupabase, color: "#3FCF8E" },
  elasticsearch: { icon: SiElasticsearch, color: "#005571" },
  oracle: { icon: SiOracle, color: "#F80000" },

  // DevOps
  docker: { icon: SiDocker, color: "#2496ED" },
  kubernetes: { icon: SiKubernetes, color: "#326CE5" },
  terraform: { icon: SiTerraform, color: "#7B42BC" },
  githubactions: { icon: SiGithubactions, color: "#2088FF" },
  jenkins: { icon: SiJenkins, color: "#D24939" },
  nginx: { icon: SiNginx, color: "#009639" },
  prometheus: { icon: SiPrometheus, color: "#E6522C" },
  websocket: { icon: Cable, color: "#EE7A48" },
};

const TECH_ICON_ALIASES: Record<string, string> = {
  "Next.js": "nextjs",
  "Node.js": "nodejs",
  "Tailwind CSS": "tailwindcss",
  "Express.js": "expressjs",
  "OpenAI API": "openai",
  "OpenAI / GPT": "openai",
  AWS: "aws",
  "Google Cloud Platform": "gcp",
  "Microsoft Azure": "azure",
  "GitHub Actions": "githubactions",
  Vercel: "vercel",
  "React Native": "react",
  Flutter: "flutter",
  Swift: "swift",
  Kotlin: "kotlin",
  Firebase: "firebase",
  Expo: "react",
  Selenium: "jenkins",
  Playwright: "react",
  "REST APIs": "api",
  "scikit-learn": "scikitlearn",
  LangChain: "langchain",
  LangGraph: "langgraph",
  "AWS Bedrock": "awsbedrock",
  Claude: "claude",
  "Llama 3": "llama3",
  Gemini: "gemini",
  Chroma: "chroma",
  Pinecone: "pinecone",
  ".NET": "dotnet",
  "Ruby on Rails": "rubyonrails",
  "Apache Spark": "apachespark",
  "Objective-C": "objectivec",
  Cordova: "cordova",
  "Oracle MAF": "oraclemaf",
  "SAP Mobile Platform": "sapmobileplatform",
  DigitalOcean: "digitalocean",
  Oracle: "oracle",
  Alchemy: "alchemy",
  Scala: "scala",
  Play: "play",
  Akka: "akka",
  "Hugging Face Transformers": "huggingface",
  "Hugging Face": "huggingface",
  Pandas: "pandas",
  PyTorch: "pytorch",
  TensorFlow: "tensorflow",
  PostgreSQL: "postgresql",
  MongoDB: "mongodb",
  GraphQL: "graphql",
  Redis: "redis",
  Docker: "docker",
  Kubernetes: "kubernetes",
  Terraform: "terraform",
  Jenkins: "jenkins",
  Nginx: "nginx",
  Prometheus: "prometheus",
  Grafana: "prometheus",
  WebSocket: "websocket",
  Solidity: "solidity",
  Ethereum: "ethereum",
  Polygon: "polygon",
  Hardhat: "hardhat",
  "Web3.js": "web3js",
  FastAPI: "fastapi",
  Python: "python",
  TypeScript: "typescript",
  React: "react",
};

export function iconForTechName(name: string) {
  const key =
    TECH_ICON_ALIASES[name] ??
    name.toLowerCase().replace(/[^a-z0-9]/g, "");
  return techIconMap[key];
}
